workspace '../Examples.xcworkspace'

link_with 'BasicMenu'
xcodeproj 'BasicMenu/BasicMenu.xcodeproj'
pod 'ECSlidingViewController', :path => '../'

target :LayoutDemo do
  link_with 'LayoutDemo'
  xcodeproj 'LayoutDemo/LayoutDemo.xcodeproj'
  pod 'ECSlidingViewController', :path => '../'
end

target :TransitionFun do
  link_with 'TransitionFun'
  xcodeproj 'TransitionFun/TransitionFun.xcodeproj'
  pod 'ECSlidingViewController', :path => '../'
end

target :TransitionFun2 do
  link_with 'TransitionFun2'
  xcodeproj 'TransitionFun2/TransitionFun2.xcodeproj'
  pod 'ECSlidingViewController', :path => '../'
end
